### ISSUE TITLE
Project description checklist

### ISSUE THREAD

**Issue by bomanviktor** [bomanviktor/localhost#8]
### The Server

- [x] it **never** crashes
- [x] All requests timeout if they are taking too long
- [x] It can listen on multiple ports and instantiate multiple servers at the same time
- [x] You only use one process and one thread
- [x] It receives a request from the browser/client and send a response using the `HTTP` header and body
- [x] It is compatible with `HTTP/1.1` protocol
- [x] You can compare your results with `NGINX` which will be used as the reference
- [x] It is compatible with the last version of your chosen browser
- [x] It manages at least [`GET`, `POST`, `DELETE`] methods.
- [x] It is able to receive file uploads made by the client.
- [x] It handles cookies and sessions.
- [x] You should create default error pages for at least the following error codes [400,403,404,405,413,500].
- [x] It calls `epoll` function (or equivalent) only once for each client/server communication.
- [x] All reads and writes should pass by `epoll` or equivalent API.
- [x] All I/O operations should be non-blocking.
- [x] You should manage chunked and unchunked requests.
- [x] You should set the right status for each response.

### The CGI

- [x] Based on the file extension the server will execute the corresponding `CGI` (for example `.php` or `.py`).
- [x] You need to implement only one `CGI` of your choice.
- [x] You are allowed to fork a new process to run the `CGI`.
- [x] `CGI` expects the file to process as first argument and `EOF` as end of the body.
- [x] Pay attention to the directory where the `CGI` will run for correct relative paths handling.
- [x] The `CGI` will check `PATH_INFO` environment variable to define the full path.

### Configuration File

In the file you should be able to specify the following:

- [x] The host (server_address) and one or multiple ports for each server.
- [x] The first server for a host:port will be the default if the "server_name" didn't match any other server.
- [x] Path to custom error pages.
- [x] Limit client body size for uploads.
#### Setup routes with one or multiple of the following settings: 
- [x] Define a list of accepted HTTP methods for the route.
- [x] Define HTTP redirections.
- [x] Define a directory or a file from where the file should be searched (for example, if `/test` is rooted to `/usr/Desktop`, the URL `/test/my_page.html` will route to `/usr/Desktop/my_page.html`).
- [x] Define a default file for the route if the URL is a directory.
- [x] Specify a `CGI` to use for a certain file extension.
- [x] Turn on or off directory listing.
- [x] Set a default file to answer if the request is a directory.

> Routes won't need to support regular expressions.

> There is no need to pass through `epoll` when reading the configuration file.

### Testing your server #5 

- [x] Do stress tests with siege `-b [IP]:[PORT]`, it must stay available at all costs (availability should be up to 99.5, it will be tested during audits).
- [x] Create tests for as many cases as you can (redirections, bad configuration files, static and dynamic pages, default error pages and so on).
- [x] You will be requested to provide and explain your tests during the audits.
- [x] You can use the language you prefer to write tests, as long as they are exhaustive and the auditor can check their behavior.
- [x] Test possible memory leaks before to submit the project.
- [x] Once again, the server should never crash and never leak memory.

### Bonus

- [x] Handle at least one more `CGI`.
- [ ] Rewrite the project in another programming language (can be `C++` or `C`).
